"""Add created_at fields to post and comment

Revision ID: 6abb39bddd38
Revises: b0c39174254e
Create Date: 2022-07-29 17:19:44.557942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6abb39bddd38'
down_revision = 'b0c39174254e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('post', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'created_at')
    op.drop_column('comment', 'created_at')
    # ### end Alembic commands ###
